"""initial schema

Revision ID: 767a068db7a7
Revises: 
Create Date: 2026-07-31 18:34:00.569875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767a068db7a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('key_ciphertext', sa.Text(), nullable=False),
    sa.Column('key_last4', sa.String(length=8), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_credentials_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('class_type_presets',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('tone', sa.String(length=128), nullable=True),
    sa.Column('length_min', sa.Integer(), nullable=False),
    sa.Column('length_max', sa.Integer(), nullable=False),
    sa.Column('emoji_min', sa.Integer(), nullable=False),
    sa.Column('emoji_max', sa.Integer(), nullable=False),
    sa.Column('prompt_hints', sa.JSON(), nullable=True),
    sa.Column('quick_tags', sa.JSON(), nullable=True),
    sa.Column('card_template', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('classes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type_code', sa.String(length=32), nullable=False),
    sa.Column('type_name_custom', sa.String(length=128), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('quick_tags_custom', sa.JSON(), nullable=True),
    sa.Column('review_term', sa.String(length=32), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_klass_user_name')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_user_id'), ['user_id'], unique=False)

    op.create_table('daily_usage',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gen_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'channel', name='uq_daily_usage_uc')
    )
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_usage_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_user_id'), ['user_id'], unique=False)

    op.create_table('generation_logs',
    sa.Column('review_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_logs_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_logs_user_id'), ['user_id'], unique=False)

    op.create_table('students',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('preferred_name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('review_term', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'external_id', name='uq_user_provider_external')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('coursewares',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=512), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coursewares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coursewares_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coursewares_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coursewares_user_id'), ['user_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', name='uq_enrollment_student_class')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('style_samples',
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_samples', schema=None) as batch_op:
        batch_op.create_index('ix_style_sample_user_class', ['user_id', 'class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_samples_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_samples_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_samples_user_id'), ['user_id'], unique=False)

    op.create_table('term_summaries',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('term_label', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_review_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('term_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_summaries_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_term_summaries_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_term_summaries_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_term_summaries_user_id'), ['user_id'], unique=False)

    op.create_table('lessons',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lesson_type', sa.String(length=16), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('common_notes', sa.Text(), nullable=True),
    sa.Column('courseware_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['courseware_id'], ['coursewares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('perf_tags', sa.JSON(), nullable=True),
    sa.Column('perf_note', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ai_raw', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('score_json', sa.JSON(), nullable=True),
    sa.Column('dedup_score', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_review_student_lesson')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_student_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_reviews_org_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_class_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_user_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_org_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_class_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('term_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_summaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_term_summaries_student_id'))
        batch_op.drop_index(batch_op.f('ix_term_summaries_org_id'))
        batch_op.drop_index(batch_op.f('ix_term_summaries_class_id'))

    op.drop_table('term_summaries')
    with op.batch_alter_table('style_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_samples_user_id'))
        batch_op.drop_index(batch_op.f('ix_style_samples_org_id'))
        batch_op.drop_index(batch_op.f('ix_style_samples_class_id'))
        batch_op.drop_index('ix_style_sample_user_class')

    op.drop_table('style_samples')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_org_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_class_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('coursewares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coursewares_user_id'))
        batch_op.drop_index(batch_op.f('ix_coursewares_org_id'))
        batch_op.drop_index(batch_op.f('ix_coursewares_class_id'))

    op.drop_table('coursewares')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_org_id'))

    op.drop_table('students')
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_logs_review_id'))
        batch_op.drop_index(batch_op.f('ix_generation_logs_org_id'))

    op.drop_table('generation_logs')
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_org_id'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_date'))

    op.drop_table('daily_usage')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_user_id'))
        batch_op.drop_index(batch_op.f('ix_classes_org_id'))

    op.drop_table('classes')
    op.drop_table('class_type_presets')
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_credentials_org_id'))

    op.drop_table('api_credentials')
    # ### end Alembic commands ###
